language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
before_script: bundle exec rake db:migrate
script: 
  - bundle exec rake db:migrate
  - bundle exec rake test:prepare
  - bundle exec rake travis
